name: zambia_tourism_backend
description: REST API backend for Zambia Tourism Flutter app
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  mysql1: ^0.20.0
  crypto: ^3.0.3
  args: ^2.4.2
  dotenv: ^4.2.0
  dart_jsonwebtoken: ^2.12.2
  bcrypt: ^1.1.3
  http: ^1.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0